import { Feed } from '~/types';

const feed: Feed[] = [
  {
    title: 'Smashing Magazine',
    slug: 'smashingmagazine',
    website: 'https://www.smashingmagazine.com',
    url: 'https://www.smashingmagazine.com/feed',
    topic: ['ux', 'design', 'frontend', 'javascript', 'react'],
  },
  {
    title: 'Microsoft Dev Blog',
    slug: 'microsoft',
    website: 'https://devblogs.microsoft.com/',
    url: 'https://devblogs.microsoft.com/devops/feed/',
    topic: ['devops'],
  },
  {
    title: 'Microsoft Dev Blog',
    slug: 'microsoft',
    website: 'https://devblogs.microsoft.com/',
    url: 'https://devblogs.microsoft.com/dotnet/feed',
    topic: ['dotnet'],
  },
  {
    title: 'Rust Blog',
    slug: 'rust',
    website: 'https://blog.rust-lang.org',
    url: 'https://blog.rust-lang.org/feed.xml',
    topic: ['rust'],
  },
  {
    title: 'Real Python',
    slug: 'realpython',
    website: 'https://realpython.com',
    url: 'https://realpython.com/atom.xml?format=xml',
    topic: ['python'],
  },
  {
    title: 'Planet Python',
    slug: 'planetpython',
    website: 'https://planetpython.org/',
    url: 'https://planetpython.org/rss20.xml',
    topic: ['python'],
  },
  {
    title: 'Medium',
    slug: 'medium',
    website: 'https://medium.com/',
    url: 'https://medium.com/feed',
    categoryPath: '/tag',
    topic: [
      'ux',
      'design',
      'frontend',
      'javascript',
      'react',
      'python',
      'devops',
      'php',
      'dotnet',
      'rust',
      'graphql',
    ],
    topicOnly: true,
  },
  {
    title: 'DEV.to',
    slug: 'dev',
    website: 'https://dev.to',
    url: 'https://dev.to/feed',
    categoryPath: '/tag',
    topic: [
      'ux',
      'design',
      'frontend',
      'javascript',
      'react',
      'php',
      'rust',
      'dotnet',
      'devops',
      'python',
      'graphql',
    ],
  },
  {
    title: 'Daily JS',
    slug: 'dailyjs',
    website: 'https://medium.com/dailyjs',
    url: 'https://medium.com/feed/dailyjs',
    topic: ['frontend', 'javascript'],
  },
  // {
  //   title: 'Hacker news',
  //   slug: 'hackernews',
  //   website: 'https://hnrss.org/',
  //   url: 'https://hnrss.org/newest',
  //   query: 'q',
  //   topic: ['ux', 'design', 'frontend', 'javascript', 'react'],
  // },
];

export default feed;
